// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Webhook struct {
	ID         int64
	Path       string
	ScriptPath string
	Active     bool
	HttpMethod string
}
