// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (path, script_path, http_method)
VALUES (?, ?, ?)
RETURNING id, path, script_path, active, http_method
`

type CreateWebhookParams struct {
	Path       string
	ScriptPath string
	HttpMethod string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook, arg.Path, arg.ScriptPath, arg.HttpMethod)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ScriptPath,
		&i.Active,
		&i.HttpMethod,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = ?
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, path, script_path, active, http_method
FROM webhooks
WHERE id = ?
`

func (q *Queries) GetWebhook(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ScriptPath,
		&i.Active,
		&i.HttpMethod,
	)
	return i, err
}

const getWebhookByPath = `-- name: GetWebhookByPath :one
SELECT id, path, script_path, active, http_method
FROM webhooks
WHERE path = ? AND active = 1
`

func (q *Queries) GetWebhookByPath(ctx context.Context, path string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByPath, path)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ScriptPath,
		&i.Active,
		&i.HttpMethod,
	)
	return i, err
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, path, script_path, active, http_method
FROM webhooks
ORDER BY id
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ScriptPath,
			&i.Active,
			&i.HttpMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks
SET path = ?, script_path = ?, active = ?, http_method = ?
WHERE id = ?
`

type UpdateWebhookParams struct {
	Path       string
	ScriptPath string
	Active     bool
	HttpMethod string
	ID         int64
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Path,
		arg.ScriptPath,
		arg.Active,
		arg.HttpMethod,
		arg.ID,
	)
	return err
}
